export { default as Hero } from "./Hero"
export { default as Features } from "./Features"
export { default as Travel } from "./Travel"
export { default as Destinations } from "./Destinations"
export { default as Cta } from "./Cta"
export { default as Footer } from "./Footer"
